### ISSUE TITLE
Compatibility with gtk (crate) 0.14.0

### ISSUE THREAD

**Issue by xou816** [MicroJoe/gladis#2]
Hi :) 
I am interested in having a version of gladis that is compatible with [gtk 0.14.0](https://crates.io/crates/gtk/0.14.0). There have been quite a few changes, but the only change that affects gladis would be the renaming of `get_object` on builder to [`object`](https://gtk-rs.org/gtk3-rs/stable/latest/docs/gtk/prelude/trait.BuilderExtManual.html#tymethod.object). 
Can I submit a PR with this change? I am not sure how you would like to handle this, as it would be a breaking change!

**Comment by gagath** [comment]
Hello there!

A PR would be welcome. I do not see why we should continue to support version `0.9.*` if it is now superseded by version `0.14.*`. After reviewing your PR I can publish the crate with a `1.0.0` version release, to mark that this crate is stable and that it is not compatible with the previous version.

What do you think?

**Comment by xou816** [comment]
Sounds good to me, I'll follow up with the PR! :)
